table: 上市公司基本信息
columns:
  - name: 公司名称
  - name: 公司简称
    desc: 是公司名称的缩写，不包含'有限责任公司','有限公司'等后缀, 例如, 农丰科技, 金润发, 红太阳
  - name: 英文名称 
  - name: 关联证券 
  - name: 公司代码
    desc: 6位数字代码为'公司代码',例如'688579','337865','300006'
  - name: 曾用简称
  - name: 所属市场
  - name: 所属行业
  - name: 成立日期
  - name: 上市日期
  - name: 法人代表
  - name: 总经理
  - name: 董秘
  - name: 邮政编码
  - name: 注册地址
  - name: 办公地址
  - name: 联系电话
  - name: 传真
  - name: 官方网址
  - name: 电子邮箱
  - name: 入选指数
  - name: 主营业务
  - name: 经营范围
  - name: 机构简介
  - name: 每股面值
  - name: 首发价格
  - name: 首发募资净额
  - name: 首发主承销商
