table: 法律文书信息
columns:
  - name: 关联公司
  - name: 标题
  - name: 案号
  - name: 文书类型
  - name: 原告
    desc: 也可称为'上诉人','申请人'
  - name: 被告
    desc: 也可称为'被起诉人','被申请人','被诉人'
  - name: 原告律师事务所
  - name: 被告律师事务所
  - name: 案由
    desc: 合同纠纷, 劳务及劳务者纠纷, 劳动合同纠纷, 债券纠纷, 房屋租赁纠纷, 财产损害赔偿纠纷
  - name: 涉案金额
  - name: 判决结果
  - name: 日期
    desc: 也可称为'审理日期'
  - name: 文件名
  - name: 起诉日期
    desc: 也可称为'立案日期','起诉时间'
  - name: 法院代字
  - name: 案件类型
    desc: 民初, 民终, 执, 执保, 执恢