question: 天津七一二通信广播股份有限公司投资金额最高的子公司与投资最低的子公司注册地址所在城市分别是？
id: 10
enriched: |
  SOS;
  上市公司基本信息.公司名称:天津七一二通信广播股份有限公司包括哪些子公司关联信息？
  这些子公司关联信息中投资金额最高的子公司关联信息是什么？
  该子公司关联信息.公司名称对应的上市公司基本信息是什么？
  该上市公司基本信息.注册地址对应的通用地址省市区信息是什么？
  该通用地址省市区信息.城市是什么？
  这些子公司关联信息中投资金额最低的子公司关联信息是什么？
  该子公司关联信息.公司名称对应的上市公司基本信息是什么？
  该上市公司基本信息.注册地址对应的通用地址省市区信息是什么？
  该通用地址省市区信息.城市是什么？;
  EOS;
answer: |
  a.天津七一二通信广播股份有限公司的子公司关联信息及最高投资金额子公司信息
  [
    1.关联上市公司全称:天津七一二通信广播股份有限公司->子公司关联信息;
    2.子公司关联信息.排序(按照上市公司投资金额降序取第一高);
    3.公司名称:子公司关联信息.公司名称->上市公司基本信息;
    4.地址:上市公司基本信息.注册地址->通用地址省市区信息;
    5.城市:通用地址省市区信息.城市;
  ];
  b.天津七一二通信广播股份有限公司的子公司关联信息及最低投资金额子公司信息
  [
    1.关联上市公司全称:天津七一二通信广播股份有限公司->子公司关联信息;
    2.子公司关联信息.排序(按照上市公司投资金额升序取第一低);
    3.公司名称:子公司关联信息.公司名称->上市公司基本信息;
    4.地址:上市公司基本信息.注册地址->通用地址省市区信息;
    5.城市:通用地址省市区信息.城市;
  ];
  EOS;
