question: (2021)苏0481民初4582号的法院在哪个区县?
id: 11
enriched: |
  SOS;
  法律文书信息.案号:(2021)苏0481民初4582号案件对应的法律文书信息是什么？
  该法律文书信息.法院代字对应的法院地址代字信息是什么？
  该法院地址代字信息.法院名称对应的法院基础信息是什么？
  该法院基础信息.法院地址对应的通用地址省市区信息是什么？
  该通用地址省市区信息.区县是什么？;
  EOS;
answer: |
  SOS;
  a.(2021)苏0481民初4582号案件的区县信息
  [
    1.案号:(2021)苏0481民初4582号->法律文书信息;
    2.法院代字:法律文书信息.法院代字->法院地址代字信息;
    3.法院名称:法院地址代字信息.法院名称->法院基础信息;
    4.地址:法院基础信息.法院地址->通用地址省市区信息;
    5.区县:通用地址省市区信息.区县;
  ];
  EOS;
