question: 广汇能源股份有限公司的股票代码和股票简称是？
id: 12
enriched: |
  SOS;
  上市公司基本信息.公司名称:广汇能源股份有限公司对应的上市公司基本信息是什么？
  该上市公司基本信息.公司代码,公司简称分别是什么？;
  EOS;
answer: |
  SOS;
  a.广汇能源股份有限公司的基本信息
  [
    1.公司名称:广汇能源股份有限公司->上市公司基本信息;
    2.股票代码:上市公司基本信息.公司代码;
    3.股票简称:上市公司基本信息.公司简称;
  ];
  EOS;
