question: 请帮我查询一下浙江晨丰科技股份有限公司参与的案件有涉案金额的有哪些？涉案金额总和为？
id: 13
enriched: |
  SOS;
  上市公司基本信息.公司名称:浙江晨丰科技股份有限公司参与的法律文书信息是什么？
  这些法律文书信息中涉案金额不为零的法律文书信息有哪些？
  这些法律文书信息.案号,涉案金额分别是多少？
  这些法律文书信息.涉案金额总和是多少？;
  EOS;
answer: |
  SOS;
  a.浙江晨丰科技股份有限公司的法律文书信息
  [
    1.公司名称:浙江晨丰科技股份有限公司->法律文书信息;
    2.法律文书信息.过滤(涉案金额不等于零);
    3.案号:法律文书信息.案号;
    4.涉案金额:法律文书信息.涉案金额;
    5.涉案金额总和:法律文书信息.合计(涉案金额);
  ];
  EOS;


