question: 请问一下，浙江省丽水市景宁畲族自治县对应的区县登记的区划代码是？
id: 15
enriched: |
  SOS;
  通用地址编码.省份:浙江省,城市:丽水市,区县:景宁畲族自治县对应的通用地址编码是什么？
  该通用地址编码.区县区划代码是什么？;
  EOS;
answer: | 
  SOS;
  a.浙江省丽水市景宁畲族自治县的区县区划代码
  [
    1.省份:浙江省,城市:丽水市,区县:景宁畲族自治县->通用地址编码;
    2.区县区划代码:通用地址编码.区县区划代码;
  ];
  EOS;
