question: 审理(2019)川0129民初1361号案件的法院名称是哪个法院，地址在什么地方
id: 18
enriched: |
  SOS;
  法律文书信息.案号:(2019)川0129民初1361号案件对应的法律文书信息是什么？
  该法律文书信息.法院代字对应的法院地址代字信息是什么？
  该法院地址代字信息.法院名称对应的法院基础信息是什么？
  该法院基础信息.法院名称,法院地址分别是什么？
  EOS;
answer: |
  SOS;
  a.(2019)川0129民初1361号案件的法院名称和地址
  [ 
    1.案号:(2019)川0129民初1361号->法律文书信息;
    2.法院代字:法律文书信息.法院代字->法院地址代字信息;
    3.法院名称:法院地址代字信息.法院名称->法院基础信息;
    4.法院名称:法院基础信息.法院名称;
    5.法院地址:法院基础信息.法院地址;
  ];
  EOS;

