question: 重庆啤酒股份有限公司涉及案件中，该公司涉案金额第二高的案件选择的律师事务所的唯一码是？该事务所服务的上市公司有多少家？
id: 2
enriched: |
  SOS;
  上市公司基本信息.公司名称:重庆啤酒股份有限公司包括哪些法律文书信息
  这些法律文书信息中法律文书信息.涉案金额第二高的法律文书信息是什么？
  该法律文书信息.原告等于重庆啤酒股份有限公司吗？
  如果是，
    该法律文书信息.原告律师事务所对应的律师事务所是什么？
    该律师事务所信息.律师事务所唯一编码是什么？
    该法律文书信息.原告律师事务所对应的律师事务所业务数据是什么？
    该律师事务所业务数据.服务已上市公司是多少？
  如果不是，
    该法律文书信息.被告律师事务所对应的律师事务所是什么？
    该律师事务所信息.律师事务所唯一编码是什么？
    该法律文书信息.被告律师事务所对应的律师事务所业务数据是什么？
    该律师事务所业务数据.服务已上市公司是多少？
  EOS;
answer: |
  SOS;
  a.重庆啤酒股份有限公司涉案信息
  [
    1.公司名称:重庆啤酒股份有限公司->法律文书信息;
    2.法律文书信息.排序(按照涉案金额降序取第二高);
    3.IF(法律文书信息.原告等于重庆啤酒股份有限公司):
      3.1 律师事务所名称:法律文书信息.原告律师事务所->律师事务所信息;
      3.2 律师事务所唯一编码:律师事务所信息.律师事务所唯一编码;
      3.3 律师事务所名称:法律文书信息.原告律师事务所->律师事务所业务数据;
      3.4 服务已上市公司:律师事务所业务数据.服务已上市公司;
    4.ELSE:
      4.1 律师事务所名称:法律文书信息.被告律师事务所->律师事务所信息;
      4.2 律师事务所唯一编码:律师事务所信息.律师事务所唯一编码;
      4.3 律师事务所名称:法律文书信息.被告律师事务所->律师事务所业务数据;
      4.4 服务已上市公司:律师事务所业务数据.服务已上市公司;
  ];
  EOS;