question: 温洲明鹿基础设施投资有限公司的注册金额是多少亿元？
id: 20
enriched: 
  SOS;
  公司工商照面信息.公司名称:温洲明鹿基础设施投资有限公司对应的注册金额是多少亿元？;
  EOS;
answer: 
  SOS;
  a.温洲明鹿基础设施投资有限公司的注册金额
  [
    1.公司名称:温洲明鹿基础设施投资有限公司->公司工商照面信息;
    2.注册资本:公司工商照面信息.注册资本;
  ];
  EOS;



