question: 统一社会信用代码是913310007200456372这家公司的法人是谁
id: 21
enriched: |
  SOS;
  公司工商照面信息.统一社会信用代码:913310007200456372对应的公司名称是什么？
  该公司名称对应的公司工商照面信息是什么？
  该公司工商照面信息.法定代表人是谁？
  该公司工商照面信息.公司名称对应的上市公司基本信息是什么？
  该上市公司基本信息.法人代表是什么？
  EOS;
answer: |
  SOS;
  a.913310007200456372对应的法定代表人
  [
    1.统一社会信用代码:913310007200456372->公司名称;
    2.公司名称:公司名称->公司工商照面信息;
    2.法定代表人:公司工商照面信息.法定代表人;
    3.公司名称:公司工商照面信息.公司名称->上市公司基本信息;
    4.法人代表:上市公司基本信息.法人代表;
  ];
  EOS;


