question: (2020)赣0781民初1260号案件的审理法院的官网网址是什么
id: 22
enriched: |
  SOS;
  法律文书信息.案号:(2020)赣0781民初1260号案件对应的法律文书信息是什么？
  该法律文书信息.法院代字对应的法院地址代字信息是什么？
  该法院地址代字信息.法院名称对应的法院基础信息是什么？
  该法院基础信息.法院官网是什么？;
  EOS;
answer: |
  SOS;
  a.(2020)赣0781民初1260号案件的审理法院官网网址
  [  
    1.案号:(2020)赣0781民初1260号->法律文书信息;
    2.法院代字:法律文书信息.法院代字->法院地址代字信息;
    3.法院名称:法院地址代字信息.法院名称->法院基础信息;
    4.法院官网:法院基础信息.法院官网;
  ];
  EOS;

