question: 北京市密云区人民法院所在的区县区划代码是多少
id: 24
enriched: |
  SOS;
  法院基础信息.法院名称:北京市密云区人民法院对应的法院基础信息是什么？
  该法院基础信息.法院地址对应的通用地址省市区信息是什么？
  该通用地址省市区信息.省份,城市,区县对应的通用地址编码是什么？
  该通用地址编码.区县区划代码是什么？;
  EOS;'
answer: |
  SOS;
  a.北京市密云区人民法院的区县区划代码
  [
    1.法院名称:北京市密云区人民法院->法院基础信息;
    2.地址:法院基础信息.法院地址->通用地址省市区信息;
    3.省份:通用地址省市区信息.省份,城市:通用地址省市区信息.城市,区县:通用地址省市区信息.区县->通用地址编码;
    4.区县区划代码:通用地址编码.区县区划代码;
  ];
  EOS;



