question: 廊坊市凯宏家居广场有限公司的统一信用代码是？投资该公司的母公司是？被投资的比例与金额分别是？该公司2019年是否被起诉次数及涉案总额为？
id: 25
enriched: | 
  SOS;
  公司工商照面信息.公司名称:廊坊市凯宏家居广场有限公司对应的统一社会信用代码是什么？
  子公司关联信息.公司名称:廊坊市凯宏家居广场有限公司对应的子公司关联信息是什么？
  该子公司关联信息.关联上市公司全称,上市公司参股比例,上市公司投资金额是多少？
  法律文书信息.关联公司:廊坊市凯宏家居广场有限公司是否包括法律文书信息？
  法律文书信息.关联公司:廊坊市凯宏家居广场有限公司是否包括法律文书信息.起诉日期为2019年且法律文书信息.被告为廊坊市凯宏家居广场有限公司的法律文书信息？
  如果是，
    这些法律文书总计有多少？
    这些法律文书信息.涉案金额总和是多少？;
  EOS;
answer: |
  SOS;
  a.廊坊市凯宏家居广场有限公司的工商照面及子公司关联信息
  [
    1.公司名称:廊坊市凯宏家居广场有限公司->公司工商照面信息;
    2.统一社会信用代码:公司工商照面信息.统一社会信用代码;
    3.公司名称:廊坊市凯宏家居广场有限公司->子公司关联信息;
    4.关联上市公司全称:子公司关联信息.关联上市公司全称;
    5.上市公司参股比例:子公司关联信息.上市公司参股比例;
    6.上市公司投资金额:子公司关联信息.上市公司投资金额;
    7.公司名称:廊坊市凯宏家居广场有限公司->法律文书信息;
    8.法律文书信息.过滤(起诉日期为2019年且被告为廊坊市凯宏家居广场有限公司);
    9.IF(法律文书信息.存在()):
      9.1 法律文书总数:法律文书信息.总计();
      9.2 涉案金额总和:法律文书信息.合计(涉案金额);
  ];
  EOS;


