question: 91320722MA27RF9U87这家公司被投资了多少万
id: 26
enriched: |
  SOS;
  公司工商照面信息.统一社会信用代码:91320722MA27RF9U87对应的公司名称是什么？
  该公司名称对应的子公司关联信息是什么？
  该子公司关联信息.上市公司投资金额是多少万？
  EOS;
answer: |
  SOS;
  a.91320722MA27RF9U87对应的子公司投资金额
  [  
    1.统一社会信用代码:91320722MA27RF9U87->公司名称;
    2.公司名称:公司名称->子公司关联信息;
    3.上市公司投资金额:子公司关联信息.上市公司投资金额;
  ];
  EOS;


