question: 2019苏0214民初6847号的关联公司是？他属于原告还是被告？判决结果是
id: 27
enriched: |
  SOS;
  法律文书信息.案号:2019苏0214民初6847号案件对应的法律文书信息是什么？
  该法律文书信息.关联公司是什么？
  该法律文书信息.原告等于法律文书信息.关联公司吗？
  如果是
    法律文书信息.关联公司是原告
  如果不是
    法律文书信息.关联公司不是原告
  该法律文书信息.判决结果是什么？;
  EOS;
answer: |
  SOS;
  a.2019苏0214民初6847号案件的法律文书信息及关联公司身份
  [
    1.案号:2019苏0214民初6847号->法律文书信息;
    2.关联公司:法律文书信息.关联公司;
    3.IF(法律文书信息.原告 等于 法律文书信息.关联公司):
      3.1 关联公司是原告:True;
    4.ELSE:
      4.1 关联公司是原告:False;
    5.判决结果:法律文书信息.判决结果;
  ];
  EOS;


