question: 上海东方华银律师事务所服务已上市公司的数量是多少家？
id: 28
enriched: |
  SOS;
  律师事务所信息.律师事务所名称:上海东方华银律师事务所对应的律师事务所业务数据是什么？
  该律师事务所业务数据.服务已上市公司是多少家？;
  EOS;
answer: |
  SOS;
  a.上海东方华银律师事务所的业务数据
  [
    1.律师事务所名称:上海东方华银律师事务所->律师事务所业务数据;
    2.服务已上市公司:律师事务所业务数据.服务已上市公司;
  ];
  EOS;


