question: (2020)浙0782民初17739号被告所请的律师事务所的登记机关是？
id: 29
enriched: |
  SOS;
  法律文书信息.案号:(2020)浙0782民初17739号案件对应的法律文书信息是什么？
  该法律文书信息.被告律师事务所对应的律师事务所信息是什么？
  该律师事务所信息.律所登记机关是什么？
  EOS;
answer: |
  SOS;
  a.(2020)浙0782民初17739号案件的被告律师事务所登记机关
  [
    1.案号:(2020)浙0782民初17739号->法律文书信息;
    2.律师事务所名称:法律文书信息.被告律师事务所->律师事务所信息;
    3.律所登记机关:律师事务所信息.律所登记机关;
  ];
  EOS;

