question: 伊吾广汇矿业有限公司作为被告的案件中涉案金额小于100万大于1万的案号分别为？涉案金额数值为？
id: 3
enriched: | 
  SOS;
  上市公司基本信息.公司名称:伊吾广汇矿业有限公司作为法律文书信息.被告且法律文书信息.涉案金额在1万至100万之间的案件法律文书信息是什么？
  这些法律文书信息.案号,涉案金额分别是多少？;
  EOS;
answer: |
  SOS;
  a.伊吾广汇矿业有限公司作涉案情况
  [
    1.公司名称:伊吾广汇矿业有限公司->法律文书信息;
    2.法律文书信息.过滤(被告等于伊吾广汇矿业有限公司,涉案金额大于1万小于100万);
    3.案号:法律文书信息.案号;
    4.涉案金额:法律文书信息.涉案金额;
  ];
  EOS;
