question: 天通股份的参保人数有多少人？
id: 30
enriched: |
  SOS;
  上市公司基本信息.公司简称:天通股份对应的上市公司基础信息是什么？
  该上市公司基础信息.公司名称对应的公司工商照面信息是什么？
  该公司工商照面信息.参保人数是多少人？;
  EOS;
answer: |
  SOS;
  a.天通股份的参保人数
  [
    1.公司简称:天通股份->上市公司基本信息;
    2.公司名称:上市公司基本信息.公司名称->公司工商照面信息;
    3.参保人数:公司工商照面信息.参保人数;
  ];
  EOS;

