question: 株洲宏达恒芯电子有限公司作为原告的案件是在什么地方审理的
id: 31
enriched: |
  SOS;
  上市公司基本信息.公司名称:株洲宏达恒芯电子有限公司包括哪些法律文书信息？
  这些法律文书信息.原告等于株洲宏达恒芯电子有限公司的法律文书信息是哪些？
  这些法律文书信息.法院代字对应的法院地址代字信息是什么？
  这些法院地址代字信息.法院名称对应的法院基础信息是什么？
  这些法院基础信息.法院地址是什么？
  EOS;
answer: |
  SOS;
  a.株洲宏达恒芯电子有限公司的法律文书信息及法院基础信息
  [  
    1.公司名称:株洲宏达恒芯电子有限公司->法律文书信息;
    2.法律文书信息.过滤(原告等于株洲宏达恒芯电子有限公司);
    3.法院代字:法律文书信息.法院代字->法院地址代字信息;
    4.法院名称:法院地址代字信息.法院名称->法院基础信息;
    5.法院地址:法院基础信息.法院地址;
  ];
  EOS;


