question: 沈阳先锋工程机械销售有限公司涉及案件中，该公司作为原告的涉案金额第二高的案件选择的律师事务所的成立时间是？
id: 32
enriched: |
  SOS;
  上市公司基本信息.公司名称:沈阳先锋工程机械销售有限公司包括哪些法律文书信息？
  这些法律文书信息.原告等于沈阳先锋工程机械销售有限公司的法律文书信息是哪些？
  这些法律文书信息中涉案金额第二高的法律文书信息是什么？
  该法律文书信息.原告律师事务所对应的律师事务所信息是什么？
  该律师事务所信息.事务所成立日期是什么？
  EOS;
answer: |
  SOS;
  a.沈阳先锋工程机械销售有限公司的法律文书及律师事务所信息
  [
    1.公司名称:沈阳先锋工程机械销售有限公司->法律文书信息;
    2.法律文书信息.过滤(原告等于沈阳先锋工程机械销售有限公司);
    3.法律文书信息.排序(按照涉案金额降序取第二高);
    4.律师事务所名称:法律文书信息.原告律师事务所->律师事务所信息;
    5.事务所成立日期:律师事务所信息.事务所成立日期;
  ];
  EOS;

