question: (2021)鲁02民终5878号案件的原告律师事务所业务量排名是第几名
id: 33
enriched: |
  SOS;
  法律文书信息.案号:(2021)鲁02民终5878号案件对应的法律文书信息是什么？
  该法律文书信息.原告律师事务所对应的律师事务所业务数据是什么？
  该律师事务所业务数据.业务量排名是第几名？
  EOS;
answer: |
  SOS;
  a.(2021)鲁02民终5878号案件的原告律师事务所业务量排名
  [
    1.案号:(2021)鲁02民终5878号->法律文书信息;
    2.律师事务所名称:法律文书信息.原告律师事务所->律师事务所业务数据;
    3.业务量排名:律师事务所业务数据.业务量排名;
  ];
  EOS;