question: 中山华利实业集团股份有限公司注册与办公的登记地址是否相同？该公司投资的子公司有多少家？投资总额为多少？
id: 34
enriched: |
  SOS;
  上市公司基本信息.公司名称:中山华利实业集团股份有限公司对应的上市公司基本信息是什么？
  该上市公司基本信息.注册地址与办公地址是否相同？
  子公司关联信息.联上市公司全称:中山华利实业集团股份有限公司包括哪些子公司关联信息？
  这些子公司关联信息一共有多少家？
  这些子公司关联信息.上市公司投资金额总和是多少？;
  EOS;
answer: |
  SOS;
  a.中山华利实业集团股份有限公司基本信息及地址对比
  [
    1.公司名称:中山华利实业集团股份有限公司->上市公司基本信息;
    2.IF(上市公司基本信息.注册地址 等于 上市公司基本信息.办公地址)
      2.1 注册地址与办公地址相同: True
  ];
  b.中山华利实业集团股份有限公司的子公司关联信息
  [
    1.关联上市公司全称:中山华利实业集团股份有限公司->子公司关联信息;
    2.子公司总数:子公司关联信息.总计();
    3.投资金额总和:子公司关联信息.合计(上市公司投资金额);
  ];
  EOS;
