question: 金堆城钼业股份有限公司投资过亿的全资子公司分别是？这些公司的统一社会信用代码及注册地址所在区县为？
id: 35
enriched: |
  SOS;
  上市公司基本信息.公司名称:金堆城钼业股份有限公司包括哪些子公司关联信息？
  这些子公司关联信息中上市公司参股比例为100%且上市公司投资金额大于1亿的子公司关联信息是什么？
  这些子公司关联信息.公司名称对应的公司工商照面信息是什么？
  这些公司工商照面信息.统一社会信用代码是什么？
  这些子公司关联信息.公司名称对应的上市公司基本信息是什么？
  这些上市公司基本信息.注册地址对应的通用地址省市区信息是什么？
  这些通用地址省市区信息.区县是什么？;
  EOS;
answer: 
  SOS;
  a.金堆城钼业股份有限公司的子公司关联信息及工商照面信息
  [  
    1.关联上市公司全称:金堆城钼业股份有限公司->子公司关联信息;
    2.子公司关联信息.过滤(上市公司参股比例等于100% 且 上市公司投资金额大于1亿);
    3.公司名称:子公司关联信息.公司名称->公司工商照面信息;
    4.统一社会信用代码:公司工商照面信息.统一社会信用代码;
    5.公司名称:子公司关联信息.公司名称->上市公司基本信息;
    6.地址:上市公司基本地址.注册地址->通用地址省市区信息;
    7.区县:通用地址省市区信息.区县;
  ];
  EOS;


