question: 统一社会信用代码为91420100568359390C的公司，我想知道其公司名称以及他在工商信息记录中的成立日期是哪一天?企业参保人数有多少?另外他在上市公司信息中记录的首发募资净额是多少?最后他旗下有多少家子公司
id: 37
enriched: |
  SOS;
  公司工商照面信息.统一社会信用代码:91420100568359390C对应的公司名称是什么？
  该公司名称对应的公司工商照面信息是什么？
  该公司工商照面信息.成立日期是什么？
  该公司工商照面信息.参保人数是多少？
  该公司名称对应的上市公司基本信息是什么？
  该上市公司基本信息.首发募资净额是多少？
  子公司关联信息.关联上市公司全称:该公司名称包括哪些子公司关联信息？
  这些子公司关联信息一共有多少家？;
  EOS;
answer: |
  SOS;
  a.91420100568359390C对应的工商照面及上市公司信息
  [  
    1.统一社会信用代码:91420100568359390C->公司名称;
    2.公司名称:公司名称->公司工商照面信息;  
    3.成立日期:公司工商照面信息.成立日期;  
    4.参保人数:公司工商照面信息.参保人数;  
    5.公司名称:公司名称->上市公司基本信息;
    6.首发募资净额:上市公司基本信息.首发募资净额;
    7.关联上市公司全称:公司名称->子公司关联信息;
    8.子公司总数:子公司关联信息.总计();
  ];
  EOS;

