question: 查询一下北京淳中科技股份有限公司涉及的案件中，于2019年立案合同相关的纠纷案件涉案不为零的案件有几次？涉案金额总和为？案号分别是？该公司的统一社会信用代码是？
id: 38
enriched: |
  SOS;
  上市公司基本信息.公司名称:北京淳中科技股份有限公司包括哪些法律文书信息？
  这些法律文书信息中法律文书信息.起诉日期:2019年 且 法律文书信息.案由:合同纠纷 且 法律文书信息.涉案金额不为零的法律文书信息是哪些？
  这些法律文书的总计有多少？
  这些法律文书信息.案号,涉案金额分别是多少？
  这些法律文书信息.涉案金额总和是多少？
  该公司名称对应的公司工商照面信息是什么？
  该公司工商照面信息.统一社会信用代码是什么？
  EOS;
answer: 
  SOS;
  a.北京淳中科技股份有限公司的法律文书信息及公司工商照面信息
  [
    1.公司名称:北京淳中科技股份有限公司->法律文书信息;
    2.法律文书信息.过滤(起诉日期等于2019年, 案由等于合同纠纷, 涉案金额不等于零);
    3.涉案次数:法律文书信息.总计()
    4.案号:法律文书信息.案号;
    5.涉案金额:法律文书信息.涉案金额;
    6.涉案金额总和:法律文书信息.合计(涉案金额);  
    7.公司名称:北京淳中科技股份有限公司->公司工商照面信息;
    8.统一社会信用代码:公司工商照面信息.统一社会信用代码;
  ];
  EOS;


