question: 我想了解四川鑫达新能源科技有限公司涉及的案件中，起诉时间发生于2020年发生的民事初审案件有几次？案号分别是？
id: 39
enriched: 
  SOS;
  上市公司基本信息.公司名称:四川鑫达新能源科技有限公司包括哪些法律文书信息？
  这些法律文书信息中起诉日期在2020年且案件类型为''民初''的法律文书信息是哪些？
  这些法律文书的总数是多少？
  这些法律文书信息.案号分别是多少？;
  EOS;
answer: |
  SOS;
  a.四川鑫达新能源科技有限公司的法律文书信息
  [
    1.公司名称:四川鑫达新能源科技有限公司->法律文书信息;
    2.法律文书信息.过滤(起诉日期等于2020年, 案件类型等于'民初');
    3.涉案次数:法律文书信息.总计();
    4.案号:法律文书信息.案号;
  ];
  EOS;

