question: 安徽安科恒益药业有限公司注册地址所在区县是？
id: 40
enriched: |
  SOS;
  上市公司基本信息.公司名称:安徽安科恒益药业有限公司对应的上市公司基本信息是什么？
  该上市公司基本信息.注册地址对应的通用地址省市区信息是什么？
  该通用地址省市区信息.区县是什么？;
  EOS;
answer: |
  SOS;
  a.安徽安科恒益药业有限公司的注册地址区县
  [
    1.公司名称:安徽安科恒益药业有限公司->上市公司基本信息;
    2.地址:上市公司基本信息.注册地址->通用地址省市区信息;
    3.区县:通用地址省市区信息.区县;
  ];
  EOS;


