question: 最近有个涉诉案号(2021)京0108民初8641号让我有点烦恼。请问原告方公司的传真和统一社会信用代码是多少？另外，麻烦你帮我查一下他们公司注册地址的城市区划代码是多少？
id: 41
enriched: |
  SOS;
  法律文书信息.案号:(2021)京0108民初8641号案件对应的法律文书信息是什么？
  该法律文书信息.原告对应的上市公司基本信息是什么？
  该上市公司基本信息.传真,注册地址分别是什么？
  该法律文书信息.原告对应的公司工商照面信息是什么？
  该公司工商照面信息.统一社会信用代码是什么？
  该注册地址对应的通用地址编码.城市区划代码是什么？
  EOS;
answer: |
  SOS;
  a.(2021)京0108民初8641号案件的法律文书及关联信息
  [
    1.案号:(2021)京0108民初8641号->法律文书信息;
    2.公司名称:法律文书信息.原告->上市公司基本信息;
    3.传真:上市公司基本信息.传真;
    4.注册地址:上市公司基本信息.注册地址;
    5.公司名称:法律文书信息.原告->公司工商照面信息;
    6.统一社会信用代码:公司工商照面信息.统一社会信用代码;
    7.地址:上市公司基本信息.注册地址->通用地址编码;
    8.城市区划代码:通用地址编码.城市区划代码;
  ];
  EOS;


