question: 陕西建设机械股份有限公公的统一社会代码是？注册资本是多少亿元？该公司的涉案次数为？作为被起诉人的次数为？
id: 42
enriched: 
  SOS;
  公司工商照面信息.公司名称:陕西建设机械股份有限公司对应的公司工商照面信息是什么？
  该公司工商照面信息的统一社会信用代码是什么？
  上市公司基本信息.公司名称:陕西建设机械股份有限公司对应的上市公司基本信息是什么？
  该上市公司基本信息.注册资本是多少？
  法律文书信息.关联公司:陕西建设机械股份有限公司包括哪些法律文书信息？
  这些法律文书信息的总数是多少？
  法律文书信息.被告:陕西建设机械股份有限公司的法律文书信息有多少？;
  EOS;
answer: 
  SOS;
  a.陕西建设机械股份有限公司的工商照面及上市公司信息
  [
    1.公司名称:陕西建设机械股份有限公司->公司工商照面信息;
    2.统一社会信用代码:公司工商照面信息.统一社会信用代码;
    3.注册资本:公司工商照面信息.注册资本;
    4.公司名称:陕西建设机械股份有限公司->法律文书信息;
    5.法律文书总数:法律文书信息.总计();
    6.法律文书信息.过滤(被告等于陕西建设机械股份有限公司);
    7.被告法律文书数:法律文书信息.总计();
  ];
  EOS;

