question: (2021)渝0109执1932号的原告是否为上市公司，如果是的话，他的股票代码和上市日期分别是？如果不是的话，统一社会信用代码是？
id: 43
enriched: |
  SOS;
  法律文书信息.案号:(2021)渝0109执1932号案件对应的法律文书信息是什么？
  该法律文书信息.原告对应的上市公司基本信息是什么？
  该上市公司基本信息是否存在？
  如果是，
    该上市公司基本信息.公司代码是什么？
    该上市公司基本信息.上市日期是什么？
  如果不是，
    该法律文书信息.原告对应的公司工商照面信息是什么？
    该公司工商照面信息.统一社会信用代码是什么？;
  EOS;
answer: |
  SOS;
  a.(2021)渝0109执1932号案件的法律文书及关联信息
  [
    1.案号:(2021)渝0109执1932号->法律文书信息;
    2.公司名称:法律文书信息.原告->上市公司基本信息;
    3.IF(上市公司基本信息.存在()):
      3.1 公司代码:上市公司基本信息.公司代码;
      3.2 上市日期:上市公司基本信息.上市日期; 
    4.ELSE:    
      4.1 公司名称:法律文书信息.原告->公司工商照面信息;
      4.2 统一社会信用代码:公司工商照面信息.统一社会信用代码;
  ];
  EOS;

