question: 创业慧康科技股份有限公司涉及案件中，涉案金额最高的申请人选择的律师事务所的地址所在区县是？
id: 44
enriched: |
  SOS;
  上市公司基本信息.公司名称:创业慧康科技股份有限公司包括哪些法律文书信息？
  这些法律文书信息中法律文书信息.涉案金额最高的法律文书信息是什么？
  该法律文书信息.原告律师事务所对应的律师事务所信息是什么？
  该律师事务所信息.律师事务所地址对应的通用地址省市区信息是什么？
  该通用地址省市区信息.区县是什么？
  EOS;
answer: |
  SOS;
  a.创业慧康科技股份有限公司的法律文书及律师事务所信息
  [
    1.公司名称:创业慧康科技股份有限公司->法律文书信息;
    2.法律文书信息.排序(按照涉案金额降序取第一高);
    3.律师事务所名称:法律文书信息.原告律师事务所->律师事务所信息;
    4.地址:律师事务所信息.律师事务所地址->通用地址省市区信息;
    5.区县:通用地址省市区信息.区县;
  ];
  EOS;


