question: 安徽合力叉车销售有限公司涉案金额最高的法院的负责人是？
id: 46
enriched: |
  SOS;
  上市公司基本信息.公司名称:安徽合力叉车销售有限公司包括哪些法律文书信息？
  这些法律文书信息中法律文书信息.涉案金额最高的法律文书信息是什么？
  该法律文书信息.法院代字对应的法院地址代字信息是什么？
  该法院地址代字信息.法院名称对应的法院基础信息是什么？
  该法院基础信息.法院负责人是谁？;
  EOS;
answer: |
  SOS;
  a.安徽合力叉车销售有限公司的涉案信息
  [
    1.公司名称:安徽合力叉车销售有限公司->法律文书信息;
    2.法律文书信息.排序(按照涉案金额降序取第一高);  
    3.法院代字:法律文书信息.法院代字->法院地址代字信息;
    4.法院名称:法院地址代字信息.法院名称->法院基础信息;
    5.法院负责人:法院基础信息.法院负责人;
  ];
  EOS;

