question: 统一代码9165292274222840XN这家公司作为原告的案件中，它雇佣的律师事务所的联系方式是什么
id: 48
enriched: 
  SOS;
  公司工商照面信息.统一社会信用代码:9165292274222840XN对应的公司名称是什么？
  该公司名称包括哪些法律文书信息？
  这些法律文书信息.原告等于该公司名称的法律文书信息是哪些？
  这些法律文书信息.原告律师事务所对应的律师事务所信息是什么？
  该律师事务所信息.通讯电话和通讯邮箱分别是什么？
  EOS;
answer: 
  SOS;
  a.9165292274222840XN对应的律师事务所的联系方式
  [
    1.统一社会信用代码:9165292274222840XN->公司名称;
    2.公司名称:公司名称->法律文书信息;  
    3.法律文书信息.过滤(原告等于公司名称);
    4.律师事务所名称:法律文书信息.原告律师事务所->律师事务所信息;
    5.通讯电话:律师事务所信息.通讯电话;
    6.通讯邮箱:律师事务所信息.通讯邮箱;
  ];
  EOS;

