question: 原告是300077案件审理法院是什么时候成立的
id: 49
enriched: 
  SOS;
  公司代码:300077对应的上市公司基本信息是什么？
  上市公司基本信息.公司名称包括哪些法律文书信息？
  这些法律文书信息.原告等于上市公司基本信息.公司名称的法律文书信息是哪些？
  这些法律文书信息.法院代字对应的法院地址代字信息是什么？
  这些法院地址代字信息.法院名称对应的法院基础信息是什么？
  这些法院基础信息.成立日期是什么？
  EOS;
answer: 
  SOS;
  a.公司代码300077的上市公司基本信息及关联法律文书信息
  [
    1.公司代码:300077->上市公司基本信息;
    2.公司名称:上市公司基本信息.公司名称->法律文书信息;
    3.法律文书信息.过滤(原告等于上市公司基本信息.公司名称);
    4.法院代字:法律文书信息.法院代字->法院地址代字信息;
    5.法院名称:法院地址代字信息.法院名称->法院基础信息;
    6.成立日期:法院基础信息.成立日期;
  ];
  EOS;

