question: 91411625MA40GA2H02这家公司的母公司一共有多少家子公司?
id: 5
enriched: | 
  SOS;
  公司工商照面信息.统一社会信用代码:91411625MA40GA2H02对应的公司名称是什么？
  该公司名称对应的子公司关联信息是什么？
  该子公司关联信息.关联上市公司全称包括多少子公司关联信息？
  这些子公司关联信息.公司名称是什么？
  这些子公司关联信息一共有多少家？
  EOS;
answer: | 
  SOS;
  a.91411625MA40GA2H02母公司的子公司数量
  [
    1.统一社会信用代码:91411625MA40GA2H02->公司名称;
    2.公司名称:公司名称->子公司关联信息;
    3.关联上市公司全称:子公司关联信息.关联上市公司全称->子公司关联信息;
    4.公司名称:子公司关联信息.公司名称;
    5.子公司总数:子公司关联信息.总计();
  ];
  EOS;
