question: (2020)皖1203民初3884号案件的被告律师事务所地址在什么地方
id: 51
enriched: 
  SOS;
  法律文书信息.案号:(2020)皖1203民初3884号案件对应的法律文书信息是什么？
  该法律文书信息.被告律师事务所对应的律师事务所信息是什么？
  该律师事务所信息.律师事务所地址是什么？
  EOS;
answer: 
  SOS;
  a.(2020)皖1203民初3884号案件的被告律师事务所地址
  [  
    1.案号:(2020)皖1203民初3884号->法律文书信息;
    2.律师事务所名称:法律文书信息.被告律师事务所->律师事务所信息;
    3.律师事务所地址:律师事务所信息.律师事务所地址;
  ];
  EOS;
