question: 保定市天威西路2222号地址对应的省市区县分别是？
id: 9
enriched: |
  SOS;
  通用地址省市区信息表.地址:保定市天威西路2222号对应的通用地址省市区信息是什么？
  该通用地址省市区信息表.省份,城市,区县分别是什么？;
  EOS;
answer: |
  SOS;
  a.保定市天威西路2222号的地址信息
  [
    1.地址:保定市天威西路2222号->通用地址省市区信息表;
    2.省份:通用地址省市区信息表.省份;
    3.城市:通用地址省市区信息表.城市;
    4.区县:通用地址省市区信息表.区县;
  ];
  EOS;
