routes:
  - 用公司名称可查询上市公司基础信息;
  - 用公司简称可查询上市公司基础信息,例如:公司简称:XXX->上市公司基本信息;
  - 用公司代码可查询上市公司基础信息;
  - 用公司名称可查询公司工商照面信息;
  - 用统一社会信息代码可查询公司名称;
  - 用公司名称可查询法律文书信息;
  - 用公司名称可查询子公司关联信息;
  - 用关联上市公司全称可查询子公司关联信息;
  - 用案号可查询法律文书信息;
  - 用案号可查询法院代字;
  - 用法院名称可查询法院基础信息;
  - 用法院名称可查询法院地址代字信息;
  - 用法院代字可查询法院地址代字信息;
  - 用律师事务所名称可查询律师事务所信息;
  - 用律师事务所名称可查询律师事务所业务数据;
  - 用地址可查询通用地址省市区信息;
  - 用省份,城市,区县可查询通用地址编码;


